version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Execute Create / Update Stack
          command: |
            aws cloudformation deploy --stack-name SampleStack --template-file infrastructure.yml \
            --parameter-overrides ParameterKey=MyIpParameter,ParameterValue=$(curl -s ifconfig.me) \
              ParameterKey=DBName,ParameterValue=${DBName} \
              ParameterKey=DBUserName,ParameterValue=${DBUserName} \
              ParameterKey=DBPassword,ParameterValue=${DBPassword}
            aws cloudformation wait stack-create-complete --stack-name SampleStack

workflows:
  sample-workflow:
    jobs:
      - cloudformation
