version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  # ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Execute Create / Update Stack
          no_output_timeout: 20m
          command: |
            aws cloudformation deploy \
              --stack-name SampleStack \
              --template-file infrastructure.yml \
              --parameter-overrides MyIpParameter=$MyIpParameter \
                DBName=$DBName \
                DBUserName=$DBUserName \
                DBPassword=$DBPassword \
              --no-fail-on-empty-changeset

  ansible-playbook:
    executor: aws-cli/default
    # executor: ansible-playbook/default
    # docker:
    #   - image: circleci/python
    steps:
      - checkout
      - aws-cli/setup
      - add_ssh_keys:
          fingerprints:
            - "e7:5c:dc:6d:c6:00:25:45:5d:12:fc:59:2f:02:bf:f3"
      - run:
          name: Add Public IPs to ansible inventory
          command: |
            aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=WebServer" \
              --query "Reservations[*].Instances[0].PublicIpAddress" \
              --output text >> ansible/inventory.ini
      - run:
          name: Install ansible
          command: |
            pip3 install ansible --user ansible
      - run:
          name: Execute Playbook
          command: |
            cat ansible/inventory.ini
            ansible-playbook -i ansible/inventory.ini ansible/test.yml -u ec2-user

      # - ansible-playbook/install:
      #     version: "2.10.7"
      # - ansible-playbook/playbook:
      #     inventory: ANSIBLE_INVENTORY
      #     playbook: ansible/test.yml
      #     private-key: ANSIBLE_SSH_KEY
      #     playbook-options: -u ec2-user

workflows:
  sample-workflow:
    jobs:
      - cloudformation
      - ansible-playbook:
          requires:
            - cloudformation
