version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Execute Create / Update Stack
          no_output_timeout: 20m
          command: |
            aws cloudformation deploy \
              --stack-name SampleStack \
              --template-file infrastructure.yml \
              --parameter-overrides MyIpParameter="$(curl -s ifconfig.me)" \
                DBName=$DBName \
                DBUserName=$DBUserName \
                DBPassword=$DBPassword \
              --no-fail-on-empty-changeset

workflows:
  sample-workflow:
    jobs:
      - cloudformation
