version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  # Document: https://circleci.com/developer/orbs/orb/orbss/ansible-playbook
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Execute Create / Update Stack
          no_output_timeout: 20m
          command: |
            aws cloudformation deploy \
              --stack-name SampleStack \
              --template-file infrastructure.yml \
              --parameter-overrides MyIpParameter=$MyIpParameter \
                DBName=$DBName \
                DBUserName=$DBUserName \
                DBPassword=$DBPassword \
              --no-fail-on-empty-changeset

  ansible-playbook:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e7:5c:dc:6d:c6:00:25:45:5d:12:fc:59:2f:02:bf:f3"
      - ansible-playbook/install:
          version: "2.12.2"
      - ansible-playbook/playbook:
          inventory: ANSIBLE_INVENTORY
          playbook: ansible/test.yml
          private-key: ANSIBLE_SSH_KEY
          playbook-options: -u ec2-user

workflows:
  sample-workflow:
    jobs:
      - cloudformation
      - ansible-playbook:
          requires:
            - cloudformation
